#!/usr/bin/env python3
"""Generate the Clementi-Raimondi size-calibration factor tables for the
HYDROGENIC radial model (the model micropython/atom_view.py and the device's
src/atom_cloud.cpp render).

For each element the factor is

    f[z] = CR_literature_valence_radius / hydrogenic_valence_mode_radius

so scaling a rendered atom's point cloud by f[z] makes its valence subshell
mode radius land on the Clementi-Raimondi literature value (pc/clementi_radii.py),
while the internal shell structure stays the model's own. The hydrogenic
model (slater.z_eff_radial: CR Z_eff to Z=54, Slater-rule fallback past it)
already matches CR for the lightest elements (H/He/B..Ne: f ~ 1.0) and
drifts for alkali/transition metals (f ~ 0.65) and the Slater-fallback range
(f ~ 0.2-0.45 for Z>54); the table is the inverse of the old hydrogenic
model's CR ratio. Elements without a CR literature value (Fr, Ra) get 1.0.

The PC viewer's tables-based calibration is separate (pc/atom_view_pc.py's
clementi_size_factor: CR / table valence mode); this table is for the
hydrogenic ports only.

Outputs (both generated, do not edit by hand):
    src/atom_size_calib.h             constexpr orb_real_t kAtomSizeCalibFactor[92]
    micropython/atom_size_calib.py    FACTOR tuple (index z-1)

Usage:
    python3 tools/atom_size_calib_gen.py
"""

import os
import sys

sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', 'pc'))
sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', 'micropython'))

import micropython_shim  # noqa: F401 -- CPython shim for @micropython.native
import slater  # noqa: E402
import pointcloud  # noqa: E402
import clementi_radii  # noqa: E402

A0_PM = 52.9177210903
MAX_Z = 92  # display range cap (slater.MAX_DISPLAY_Z)
MODE_RESOLUTION = 200000


def _valence_subshell(config):
    n_max = max(n for n, _ell, _occ in config)
    return max(((n, ell) for n, ell, _occ in config if n == n_max), key=lambda t: t[1])


def compute_factors():
    factors = []
    for z in range(1, MAX_Z + 1):
        lit = clementi_radii.CLEMENTI_RADIUS_PM.get(z)
        if not lit:
            factors.append(1.0)
            continue
        config = slater.electron_configuration(z)
        n, ell = _valence_subshell(config)
        z_eff = slater.z_eff_radial(z, config, n, ell)
        mode_pm = pointcloud.radial_mode_radius(n, ell, z_eff, resolution=MODE_RESOLUTION) * A0_PM
        factors.append(lit / mode_pm if mode_pm > 0.0 else 1.0)
    return factors


def emit_header(factors):
    lines = [
        "// Clementi-Raimondi size-calibration factors for the atom point cloud, indexed by",
        "// Z-1 (Z=1..92, the display range cap -- see periodic_grid.h's kMaxDisplayZ).",
        "// Scaling a rendered cloud's coordinates by kAtomSizeCalibFactor[z-1] makes its",
        "// valence subshell mode radius land on the Clementi-Raimondi literature value",
        "// (pc/clementi_radii.py), keeping the model's own internal shell structure.",
        "// Hydrogenic-model factors (slater.z_eff_radial): f = CR_lit / valence mode;",
        "// elements without a CR value (Fr, Ra) are 1.0. See pc/RUN_HFS.md and",
        "// pc/atom_view_pc.py's clementi_size_factor for the PC tables-based sibling.",
        "//",
        "// GENERATED by tools/atom_size_calib_gen.py -- do not edit by hand.",
        "#pragma once",
        "",
        '#include "orbitals.h" // orb_real_t',
        "",
        "constexpr int kAtomSizeCalibCount = %d;" % len(factors),
        "",
        "constexpr orb_real_t kAtomSizeCalibFactor[%d] = {" % len(factors),
    ]
    for i in range(0, len(factors), 4):
        chunk = ", ".join("orb_real_t(%.4f)" % f for f in factors[i:i + 4])
        lines.append("    %s," % chunk)
    lines.append("};")
    return "\n".join(lines) + "\n"


def emit_module(factors):
    rows = []
    for i in range(0, len(factors), 8):
        rows.append("    " + ", ".join("%.4f" % f for f in factors[i:i + 8]))
    return (
        '"""Clementi-Raimondi size-calibration factors for the hydrogenic atom cloud,'
        "\nindexed by Z-1 (Z=1..92, the display range cap -- slater.MAX_DISPLAY_Z)."
        "\nScaling the cloud coordinates by FACTOR[z-1] makes the valence subshell mode"
        "\nradius land on the Clementi-Raimondi literature value, keeping the model's own"
        "\ninternal shell structure. Elements without a CR value (Fr, Ra) are 1.0."
        "\nSee pc/RUN_HFS.md; the PC tables-based calibration is atom_view_pc."
        "clementi_size_factor."
        "\n"
        "\nGENERATED by tools/atom_size_calib_gen.py -- do not edit by hand."
        '\n"""'
        "\n"
        "\nFACTOR = ("
        "\n" + ",\n".join(rows) + ",\n)"
        "\n"
    )


def main():
    factors = compute_factors()
    assert len(factors) == MAX_Z
    root = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..')
    h_path = os.path.join(root, 'src', 'atom_size_calib.h')
    py_path = os.path.join(root, 'micropython', 'atom_size_calib.py')
    with open(h_path, 'w', encoding='utf-8', newline='\n') as f:
        f.write(emit_header(factors))
    with open(py_path, 'w', encoding='utf-8', newline='\n') as f:
        f.write(emit_module(factors))
    print("wrote %s (%d factors)" % (h_path, len(factors)))
    print("wrote %s" % py_path)
    print("sample: H=%.4f Li=%.4f Fe=%.4f Pd=%.4f Cs=%.4f U=%.4f" % (
        factors[0], factors[2], factors[25], factors[45], factors[54], factors[91]))
    return 0


if __name__ == '__main__':
    sys.exit(main())
