// Clementi-Raimondi size-calibration factors for the atom point cloud, indexed by
// Z-1 (Z=1..92, the display range cap -- see periodic_grid.h's kMaxDisplayZ).
// Scaling a rendered cloud's coordinates by kAtomSizeCalibFactor[z-1] makes its
// valence subshell mode radius land on the Clementi-Raimondi literature value
// (pc/clementi_radii.py), keeping the model's own internal shell structure.
// Hydrogenic-model factors (slater.z_eff_radial): f = CR_lit / valence mode;
// elements without a CR value (Fr, Ra) are 1.0. See pc/RUN_HFS.md and
// pc/atom_view_pc.py's clementi_size_factor for the PC tables-based sibling.
//
// GENERATED by tools/atom_size_calib_gen.py -- do not edit by hand.
#pragma once

#include "orbitals.h" // orb_real_t

constexpr int kAtomSizeCalibCount = 92;

constexpr orb_real_t kAtomSizeCalibFactor[92] = {
    orb_real_t(1.0016), orb_real_t(0.9889), orb_real_t(0.7709), orb_real_t(0.7729),
    orb_real_t(0.9951), orb_real_t(0.9926), orb_real_t(1.0143), orb_real_t(1.0098),
    orb_real_t(1.0120), orb_real_t(1.0337), orb_real_t(0.6885), orb_real_t(0.6933),
    orb_real_t(0.7556), orb_real_t(0.7490), orb_real_t(0.7540), orb_real_t(0.7597),
    orb_real_t(0.7609), orb_real_t(0.7563), orb_real_t(0.6519), orb_real_t(0.6549),
    orb_real_t(0.6542), orb_real_t(0.6508), orb_real_t(0.6538), orb_real_t(0.6541),
    orb_real_t(0.6529), orb_real_t(0.6507), orb_real_t(0.6506), orb_real_t(0.6532),
    orb_real_t(0.6502), orb_real_t(0.6502), orb_real_t(0.6781), orb_real_t(0.6792),
    orb_real_t(0.6805), orb_real_t(0.6840), orb_real_t(0.6801), orb_real_t(0.6585),
    orb_real_t(0.6253), orb_real_t(0.6293), orb_real_t(0.6278), orb_real_t(0.6285),
    orb_real_t(0.5549), orb_real_t(0.5491), orb_real_t(0.6260), orb_real_t(0.5464),
    orb_real_t(0.5437), orb_real_t(2.0504), orb_real_t(0.5276), orb_real_t(0.6243),
    orb_real_t(0.6419), orb_real_t(0.6411), orb_real_t(0.6458), orb_real_t(0.6459),
    orb_real_t(0.6487), orb_real_t(0.6519), orb_real_t(0.2999), orb_real_t(0.3298),
    orb_real_t(0.2676), orb_real_t(0.2538), orb_real_t(0.3220), orb_real_t(0.2685),
    orb_real_t(0.2672), orb_real_t(0.3102), orb_real_t(0.3011), orb_real_t(0.3197),
    orb_real_t(0.2933), orb_real_t(0.2972), orb_real_t(0.2946), orb_real_t(0.2946),
    orb_real_t(0.2894), orb_real_t(0.2894), orb_real_t(0.2977), orb_real_t(0.2997),
    orb_real_t(0.3019), orb_real_t(0.3045), orb_real_t(0.3095), orb_real_t(0.3173),
    orb_real_t(0.3211), orb_real_t(0.2874), orb_real_t(0.2945), orb_real_t(0.3402),
    orb_real_t(0.3630), orb_real_t(0.4049), orb_real_t(0.4193), orb_real_t(0.4366),
    orb_real_t(0.4492), orb_real_t(0.4607), orb_real_t(1.0000), orb_real_t(1.0000),
    orb_real_t(0.2248), orb_real_t(0.2179), orb_real_t(0.2075), orb_real_t(0.2018),
};
